# Generated by Django 6.0.2 on 2026-03-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exp',
            field=models.IntegerField(default=25),
        ),
    ]
