# Generated by Django 6.0.2 on 2026-03-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
