# Generated by Django 6.0.2 on 2026-03-17 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_exp_alter_question_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exp',
        ),
    ]
