# Generated by Django 6.0.2 on 2026-03-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userattempt_options_alter_userattempt_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_answer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
